<?php
/**
 * CdsMarketplaceApiModelsOfferIntegrationDtosOfferLogDto
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOfferIntegrationDtosOfferLogDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CdsMarketplaceApiModelsOfferIntegrationDtosOfferLogDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cds.MarketplaceApi.Models.OfferIntegration.Dtos.OfferLogDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'log_date' => '\DateTime',
        'offer_integration_status' => 'string',
        'product_ean' => 'string',
        'seller_product_id' => 'string',
        'property_list' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosOfferPropertyLogDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'log_date' => 'date-time',
        'offer_integration_status' => null,
        'product_ean' => null,
        'seller_product_id' => null,
        'property_list' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'log_date' => 'log_date',
        'offer_integration_status' => 'offer_integration_status',
        'product_ean' => 'product_ean',
        'seller_product_id' => 'seller_product_id',
        'property_list' => 'property_list'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'log_date' => 'setLogDate',
        'offer_integration_status' => 'setOfferIntegrationStatus',
        'product_ean' => 'setProductEan',
        'seller_product_id' => 'setSellerProductId',
        'property_list' => 'setPropertyList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'log_date' => 'getLogDate',
        'offer_integration_status' => 'getOfferIntegrationStatus',
        'product_ean' => 'getProductEan',
        'seller_product_id' => 'getSellerProductId',
        'property_list' => 'getPropertyList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['log_date'] = $data['log_date'] ?? null;
        $this->container['offer_integration_status'] = $data['offer_integration_status'] ?? null;
        $this->container['product_ean'] = $data['product_ean'] ?? null;
        $this->container['seller_product_id'] = $data['seller_product_id'] ?? null;
        $this->container['property_list'] = $data['property_list'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets log_date
     *
     * @return \DateTime|null
     */
    public function getLogDate()
    {
        return $this->container['log_date'];
    }

    /**
     * Sets log_date
     *
     * @param \DateTime|null $log_date log_date
     *
     * @return self
     */
    public function setLogDate($log_date)
    {
        $this->container['log_date'] = $log_date;

        return $this;
    }

    /**
     * Gets offer_integration_status
     *
     * @return string|null
     */
    public function getOfferIntegrationStatus()
    {
        return $this->container['offer_integration_status'];
    }

    /**
     * Sets offer_integration_status
     *
     * @param string|null $offer_integration_status offer_integration_status
     *
     * @return self
     */
    public function setOfferIntegrationStatus($offer_integration_status)
    {
        $this->container['offer_integration_status'] = $offer_integration_status;

        return $this;
    }

    /**
     * Gets product_ean
     *
     * @return string|null
     */
    public function getProductEan()
    {
        return $this->container['product_ean'];
    }

    /**
     * Sets product_ean
     *
     * @param string|null $product_ean product_ean
     *
     * @return self
     */
    public function setProductEan($product_ean)
    {
        $this->container['product_ean'] = $product_ean;

        return $this;
    }

    /**
     * Gets seller_product_id
     *
     * @return string|null
     */
    public function getSellerProductId()
    {
        return $this->container['seller_product_id'];
    }

    /**
     * Sets seller_product_id
     *
     * @param string|null $seller_product_id seller_product_id
     *
     * @return self
     */
    public function setSellerProductId($seller_product_id)
    {
        $this->container['seller_product_id'] = $seller_product_id;

        return $this;
    }

    /**
     * Gets property_list
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosOfferPropertyLogDto[]|null
     */
    public function getPropertyList()
    {
        return $this->container['property_list'];
    }

    /**
     * Sets property_list
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosOfferPropertyLogDto[]|null $property_list property_list
     *
     * @return self
     */
    public function setPropertyList($property_list)
    {
        $this->container['property_list'] = $property_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


