<?php
/**
 * CdsMarketplaceApiModelsProductIntegrationDtosProductIntegrationState
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsProductIntegrationDtosProductIntegrationState Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CdsMarketplaceApiModelsProductIntegrationDtosProductIntegrationState
{
    /**
     * Possible values of this enum
     */
    const NONE = 'None';
    const AUTO_CHECKS_PENDING = 'AutoChecksPending';
    const AUTO_CHECKS_VALID = 'AutoChecksValid';
    const MANUAL_CHECKS_PENDING = 'ManualChecksPending';
    const MANUAL_CHECKS_VALID = 'ManualChecksValid';
    const MANUAL_CHECKS_REJECTED = 'ManualChecksRejected';
    const TO_BE_SYNCHRONIZED = 'ToBeSynchronized';
    const SYNCHRONIZATION_PENDING = 'SynchronizationPending';
    const SYNCHRONIZED = 'Synchronized';
    const ALREADY_EXISTS_IN_CATALOG = 'AlreadyExistsInCatalog';
    const INTEGRATED = 'Integrated';
    const REJECTED = 'Rejected';
    const SUBMITTED = 'Submitted';
    const EAN_REFERENCED_FOR_NON_VARIANT_PRODUCT = 'EanReferencedForNonVariantProduct';
    const DATA_IS_NOT_SERIALIZABLE = 'DataIsNotSerializable';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::AUTO_CHECKS_PENDING,
            self::AUTO_CHECKS_VALID,
            self::MANUAL_CHECKS_PENDING,
            self::MANUAL_CHECKS_VALID,
            self::MANUAL_CHECKS_REJECTED,
            self::TO_BE_SYNCHRONIZED,
            self::SYNCHRONIZATION_PENDING,
            self::SYNCHRONIZED,
            self::ALREADY_EXISTS_IN_CATALOG,
            self::INTEGRATED,
            self::REJECTED,
            self::SUBMITTED,
            self::EAN_REFERENCED_FOR_NON_VARIANT_PRODUCT,
            self::DATA_IS_NOT_SERIALIZABLE,
        ];
    }
}


