<?php
/**
 * CdsMarketplaceApiModelsOfferIntegrationPackageLog
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOfferIntegrationPackageLog Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CdsMarketplaceApiModelsOfferIntegrationPackageLog implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cds.MarketplaceApi.Models.OfferIntegration.PackageLog';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'package_id' => 'int',
        'integration_state' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosDetailedPackageIntegrationStateDto',
        'number_of_errors' => 'int',
        'offer_log_paged_list' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosOfferLogDto[]',
        'seller_id' => 'int',
        'page' => 'int',
        'count_by_page' => 'int',
        'total_logs_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'package_id' => 'int64',
        'integration_state' => null,
        'number_of_errors' => 'int32',
        'offer_log_paged_list' => null,
        'seller_id' => 'int64',
        'page' => 'int32',
        'count_by_page' => 'int32',
        'total_logs_count' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'package_id' => 'package_id',
        'integration_state' => 'integration_state',
        'number_of_errors' => 'number_of_errors',
        'offer_log_paged_list' => 'offer_log_paged_list',
        'seller_id' => 'seller_id',
        'page' => 'page',
        'count_by_page' => 'count_by_page',
        'total_logs_count' => 'total_logs_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'package_id' => 'setPackageId',
        'integration_state' => 'setIntegrationState',
        'number_of_errors' => 'setNumberOfErrors',
        'offer_log_paged_list' => 'setOfferLogPagedList',
        'seller_id' => 'setSellerId',
        'page' => 'setPage',
        'count_by_page' => 'setCountByPage',
        'total_logs_count' => 'setTotalLogsCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'package_id' => 'getPackageId',
        'integration_state' => 'getIntegrationState',
        'number_of_errors' => 'getNumberOfErrors',
        'offer_log_paged_list' => 'getOfferLogPagedList',
        'seller_id' => 'getSellerId',
        'page' => 'getPage',
        'count_by_page' => 'getCountByPage',
        'total_logs_count' => 'getTotalLogsCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['package_id'] = $data['package_id'] ?? null;
        $this->container['integration_state'] = $data['integration_state'] ?? null;
        $this->container['number_of_errors'] = $data['number_of_errors'] ?? null;
        $this->container['offer_log_paged_list'] = $data['offer_log_paged_list'] ?? null;
        $this->container['seller_id'] = $data['seller_id'] ?? null;
        $this->container['page'] = $data['page'] ?? null;
        $this->container['count_by_page'] = $data['count_by_page'] ?? null;
        $this->container['total_logs_count'] = $data['total_logs_count'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets package_id
     *
     * @return int|null
     */
    public function getPackageId()
    {
        return $this->container['package_id'];
    }

    /**
     * Sets package_id
     *
     * @param int|null $package_id package_id
     *
     * @return self
     */
    public function setPackageId($package_id)
    {
        $this->container['package_id'] = $package_id;

        return $this;
    }

    /**
     * Gets integration_state
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosDetailedPackageIntegrationStateDto|null
     */
    public function getIntegrationState()
    {
        return $this->container['integration_state'];
    }

    /**
     * Sets integration_state
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosDetailedPackageIntegrationStateDto|null $integration_state integration_state
     *
     * @return self
     */
    public function setIntegrationState($integration_state)
    {
        $this->container['integration_state'] = $integration_state;

        return $this;
    }

    /**
     * Gets number_of_errors
     *
     * @return int|null
     */
    public function getNumberOfErrors()
    {
        return $this->container['number_of_errors'];
    }

    /**
     * Sets number_of_errors
     *
     * @param int|null $number_of_errors number_of_errors
     *
     * @return self
     */
    public function setNumberOfErrors($number_of_errors)
    {
        $this->container['number_of_errors'] = $number_of_errors;

        return $this;
    }

    /**
     * Gets offer_log_paged_list
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosOfferLogDto[]|null
     */
    public function getOfferLogPagedList()
    {
        return $this->container['offer_log_paged_list'];
    }

    /**
     * Sets offer_log_paged_list
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOfferIntegrationDtosOfferLogDto[]|null $offer_log_paged_list offer_log_paged_list
     *
     * @return self
     */
    public function setOfferLogPagedList($offer_log_paged_list)
    {
        $this->container['offer_log_paged_list'] = $offer_log_paged_list;

        return $this;
    }

    /**
     * Gets seller_id
     *
     * @return int|null
     */
    public function getSellerId()
    {
        return $this->container['seller_id'];
    }

    /**
     * Sets seller_id
     *
     * @param int|null $seller_id seller_id
     *
     * @return self
     */
    public function setSellerId($seller_id)
    {
        $this->container['seller_id'] = $seller_id;

        return $this;
    }

    /**
     * Gets page
     *
     * @return int|null
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param int|null $page page
     *
     * @return self
     */
    public function setPage($page)
    {
        $this->container['page'] = $page;

        return $this;
    }

    /**
     * Gets count_by_page
     *
     * @return int|null
     */
    public function getCountByPage()
    {
        return $this->container['count_by_page'];
    }

    /**
     * Sets count_by_page
     *
     * @param int|null $count_by_page count_by_page
     *
     * @return self
     */
    public function setCountByPage($count_by_page)
    {
        $this->container['count_by_page'] = $count_by_page;

        return $this;
    }

    /**
     * Gets total_logs_count
     *
     * @return int|null
     */
    public function getTotalLogsCount()
    {
        return $this->container['total_logs_count'];
    }

    /**
     * Sets total_logs_count
     *
     * @param int|null $total_logs_count total_logs_count
     *
     * @return self
     */
    public function setTotalLogsCount($total_logs_count)
    {
        $this->container['total_logs_count'] = $total_logs_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


