<?php
/**
 * CdsMarketplaceApiModelsOrderParcelStatus
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOrderParcelStatus Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CdsMarketplaceApiModelsOrderParcelStatus
{
    /**
     * Possible values of this enum
     */
    const DELIVERED = 'Delivered';
    const NOT_DELIVERED_BACK_TRANSPORTER = 'NotDeliveredBackTransporter';
    const NOT_DELIVERED_LOST_OR_BROKEN = 'NotDeliveredLostOrBroken';
    const COMMITTED_THE_TRANSPORTER = 'CommittedTheTransporter';
    const ON_GOING_DELIVERY = 'OnGoingDelivery';
    const IN_POINT_RELAY = 'InPointRelay';
    const OTHER = 'Other';
    const PREPARED = 'Prepared';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DELIVERED,
            self::NOT_DELIVERED_BACK_TRANSPORTER,
            self::NOT_DELIVERED_LOST_OR_BROKEN,
            self::COMMITTED_THE_TRANSPORTER,
            self::ON_GOING_DELIVERY,
            self::IN_POINT_RELAY,
            self::OTHER,
            self::PREPARED,
        ];
    }
}


