<?php
/**
 * CdsMarketplaceApiModelsOrderOrder
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOrderOrder Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CdsMarketplaceApiModelsOrderOrder implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cds.MarketplaceApi.Models.Order.Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'archive_parcel_list' => 'bool',
        'billing_address' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderAddress',
        'creation_date' => '\DateTime',
        'customer' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderCustomer',
        'modified_date' => '\DateTime',
        'offer' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOfferOrder',
        'order_line_list' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderLine[]',
        'order_number' => 'string',
        'shipping_address' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderAddress',
        'initial_total_shipping_charges_amount' => 'double',
        'status' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderStatus',
        'initial_total_amount' => 'double',
        'validation_status' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderValidationStatus',
        'shipping_code' => 'string',
        'validated_total_amount' => 'double',
        'shipped_total_amount' => 'double',
        'validated_total_shipping_charges' => 'double',
        'shipped_total_shipping_charges' => 'double',
        'order_state' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderState',
        'site_commission_promised_amount' => 'double',
        'site_commission_validated_amount' => 'double',
        'site_commission_shipped_amount' => 'double',
        'last_updated_date' => '\DateTime',
        'shipping_date_max' => '\DateTime',
        'shipping_date_min' => '\DateTime',
        'has_claims' => 'bool',
        'is_c_logistique_order' => 'bool',
        'corporation' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderCorporation',
        'visa_cegid' => 'int',
        'partner_order_ref' => 'string',
        'mod_ges_log' => 'string',
        'is_eligibile_substitution' => 'bool',
        'parcel_list' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderParcel[]',
        'voucher_list' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderVoucher[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'archive_parcel_list' => null,
        'billing_address' => null,
        'creation_date' => 'date-time',
        'customer' => null,
        'modified_date' => 'date-time',
        'offer' => null,
        'order_line_list' => null,
        'order_number' => null,
        'shipping_address' => null,
        'initial_total_shipping_charges_amount' => 'double',
        'status' => null,
        'initial_total_amount' => 'double',
        'validation_status' => null,
        'shipping_code' => null,
        'validated_total_amount' => 'double',
        'shipped_total_amount' => 'double',
        'validated_total_shipping_charges' => 'double',
        'shipped_total_shipping_charges' => 'double',
        'order_state' => null,
        'site_commission_promised_amount' => 'double',
        'site_commission_validated_amount' => 'double',
        'site_commission_shipped_amount' => 'double',
        'last_updated_date' => 'date-time',
        'shipping_date_max' => 'date-time',
        'shipping_date_min' => 'date-time',
        'has_claims' => null,
        'is_c_logistique_order' => null,
        'corporation' => null,
        'visa_cegid' => 'int32',
        'partner_order_ref' => null,
        'mod_ges_log' => null,
        'is_eligibile_substitution' => null,
        'parcel_list' => null,
        'voucher_list' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'archive_parcel_list' => 'archive_parcel_list',
        'billing_address' => 'billing_address',
        'creation_date' => 'creation_date',
        'customer' => 'customer',
        'modified_date' => 'modified_date',
        'offer' => 'offer',
        'order_line_list' => 'order_line_list',
        'order_number' => 'order_number',
        'shipping_address' => 'shipping_address',
        'initial_total_shipping_charges_amount' => 'initial_total_shipping_charges_amount',
        'status' => 'status',
        'initial_total_amount' => 'initial_total_amount',
        'validation_status' => 'validation_status',
        'shipping_code' => 'shipping_code',
        'validated_total_amount' => 'validated_total_amount',
        'shipped_total_amount' => 'shipped_total_amount',
        'validated_total_shipping_charges' => 'validated_total_shipping_charges',
        'shipped_total_shipping_charges' => 'shipped_total_shipping_charges',
        'order_state' => 'order_state',
        'site_commission_promised_amount' => 'site_commission_promised_amount',
        'site_commission_validated_amount' => 'site_commission_validated_amount',
        'site_commission_shipped_amount' => 'site_commission_shipped_amount',
        'last_updated_date' => 'last_updated_date',
        'shipping_date_max' => 'shipping_date_max',
        'shipping_date_min' => 'shipping_date_min',
        'has_claims' => 'has_claims',
        'is_c_logistique_order' => 'is_c_logistique_order',
        'corporation' => 'corporation',
        'visa_cegid' => 'visa_cegid',
        'partner_order_ref' => 'partner_order_ref',
        'mod_ges_log' => 'mod_ges_log',
        'is_eligibile_substitution' => 'is_eligibile_substitution',
        'parcel_list' => 'parcel_list',
        'voucher_list' => 'voucher_list'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'archive_parcel_list' => 'setArchiveParcelList',
        'billing_address' => 'setBillingAddress',
        'creation_date' => 'setCreationDate',
        'customer' => 'setCustomer',
        'modified_date' => 'setModifiedDate',
        'offer' => 'setOffer',
        'order_line_list' => 'setOrderLineList',
        'order_number' => 'setOrderNumber',
        'shipping_address' => 'setShippingAddress',
        'initial_total_shipping_charges_amount' => 'setInitialTotalShippingChargesAmount',
        'status' => 'setStatus',
        'initial_total_amount' => 'setInitialTotalAmount',
        'validation_status' => 'setValidationStatus',
        'shipping_code' => 'setShippingCode',
        'validated_total_amount' => 'setValidatedTotalAmount',
        'shipped_total_amount' => 'setShippedTotalAmount',
        'validated_total_shipping_charges' => 'setValidatedTotalShippingCharges',
        'shipped_total_shipping_charges' => 'setShippedTotalShippingCharges',
        'order_state' => 'setOrderState',
        'site_commission_promised_amount' => 'setSiteCommissionPromisedAmount',
        'site_commission_validated_amount' => 'setSiteCommissionValidatedAmount',
        'site_commission_shipped_amount' => 'setSiteCommissionShippedAmount',
        'last_updated_date' => 'setLastUpdatedDate',
        'shipping_date_max' => 'setShippingDateMax',
        'shipping_date_min' => 'setShippingDateMin',
        'has_claims' => 'setHasClaims',
        'is_c_logistique_order' => 'setIsCLogistiqueOrder',
        'corporation' => 'setCorporation',
        'visa_cegid' => 'setVisaCegid',
        'partner_order_ref' => 'setPartnerOrderRef',
        'mod_ges_log' => 'setModGesLog',
        'is_eligibile_substitution' => 'setIsEligibileSubstitution',
        'parcel_list' => 'setParcelList',
        'voucher_list' => 'setVoucherList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'archive_parcel_list' => 'getArchiveParcelList',
        'billing_address' => 'getBillingAddress',
        'creation_date' => 'getCreationDate',
        'customer' => 'getCustomer',
        'modified_date' => 'getModifiedDate',
        'offer' => 'getOffer',
        'order_line_list' => 'getOrderLineList',
        'order_number' => 'getOrderNumber',
        'shipping_address' => 'getShippingAddress',
        'initial_total_shipping_charges_amount' => 'getInitialTotalShippingChargesAmount',
        'status' => 'getStatus',
        'initial_total_amount' => 'getInitialTotalAmount',
        'validation_status' => 'getValidationStatus',
        'shipping_code' => 'getShippingCode',
        'validated_total_amount' => 'getValidatedTotalAmount',
        'shipped_total_amount' => 'getShippedTotalAmount',
        'validated_total_shipping_charges' => 'getValidatedTotalShippingCharges',
        'shipped_total_shipping_charges' => 'getShippedTotalShippingCharges',
        'order_state' => 'getOrderState',
        'site_commission_promised_amount' => 'getSiteCommissionPromisedAmount',
        'site_commission_validated_amount' => 'getSiteCommissionValidatedAmount',
        'site_commission_shipped_amount' => 'getSiteCommissionShippedAmount',
        'last_updated_date' => 'getLastUpdatedDate',
        'shipping_date_max' => 'getShippingDateMax',
        'shipping_date_min' => 'getShippingDateMin',
        'has_claims' => 'getHasClaims',
        'is_c_logistique_order' => 'getIsCLogistiqueOrder',
        'corporation' => 'getCorporation',
        'visa_cegid' => 'getVisaCegid',
        'partner_order_ref' => 'getPartnerOrderRef',
        'mod_ges_log' => 'getModGesLog',
        'is_eligibile_substitution' => 'getIsEligibileSubstitution',
        'parcel_list' => 'getParcelList',
        'voucher_list' => 'getVoucherList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['archive_parcel_list'] = $data['archive_parcel_list'] ?? null;
        $this->container['billing_address'] = $data['billing_address'] ?? null;
        $this->container['creation_date'] = $data['creation_date'] ?? null;
        $this->container['customer'] = $data['customer'] ?? null;
        $this->container['modified_date'] = $data['modified_date'] ?? null;
        $this->container['offer'] = $data['offer'] ?? null;
        $this->container['order_line_list'] = $data['order_line_list'] ?? null;
        $this->container['order_number'] = $data['order_number'] ?? null;
        $this->container['shipping_address'] = $data['shipping_address'] ?? null;
        $this->container['initial_total_shipping_charges_amount'] = $data['initial_total_shipping_charges_amount'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['initial_total_amount'] = $data['initial_total_amount'] ?? null;
        $this->container['validation_status'] = $data['validation_status'] ?? null;
        $this->container['shipping_code'] = $data['shipping_code'] ?? null;
        $this->container['validated_total_amount'] = $data['validated_total_amount'] ?? null;
        $this->container['shipped_total_amount'] = $data['shipped_total_amount'] ?? null;
        $this->container['validated_total_shipping_charges'] = $data['validated_total_shipping_charges'] ?? null;
        $this->container['shipped_total_shipping_charges'] = $data['shipped_total_shipping_charges'] ?? null;
        $this->container['order_state'] = $data['order_state'] ?? null;
        $this->container['site_commission_promised_amount'] = $data['site_commission_promised_amount'] ?? null;
        $this->container['site_commission_validated_amount'] = $data['site_commission_validated_amount'] ?? null;
        $this->container['site_commission_shipped_amount'] = $data['site_commission_shipped_amount'] ?? null;
        $this->container['last_updated_date'] = $data['last_updated_date'] ?? null;
        $this->container['shipping_date_max'] = $data['shipping_date_max'] ?? null;
        $this->container['shipping_date_min'] = $data['shipping_date_min'] ?? null;
        $this->container['has_claims'] = $data['has_claims'] ?? null;
        $this->container['is_c_logistique_order'] = $data['is_c_logistique_order'] ?? null;
        $this->container['corporation'] = $data['corporation'] ?? null;
        $this->container['visa_cegid'] = $data['visa_cegid'] ?? null;
        $this->container['partner_order_ref'] = $data['partner_order_ref'] ?? null;
        $this->container['mod_ges_log'] = $data['mod_ges_log'] ?? null;
        $this->container['is_eligibile_substitution'] = $data['is_eligibile_substitution'] ?? null;
        $this->container['parcel_list'] = $data['parcel_list'] ?? null;
        $this->container['voucher_list'] = $data['voucher_list'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets archive_parcel_list
     *
     * @return bool|null
     */
    public function getArchiveParcelList()
    {
        return $this->container['archive_parcel_list'];
    }

    /**
     * Sets archive_parcel_list
     *
     * @param bool|null $archive_parcel_list archive_parcel_list
     *
     * @return self
     */
    public function setArchiveParcelList($archive_parcel_list)
    {
        $this->container['archive_parcel_list'] = $archive_parcel_list;

        return $this;
    }

    /**
     * Gets billing_address
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderAddress|null
     */
    public function getBillingAddress()
    {
        return $this->container['billing_address'];
    }

    /**
     * Sets billing_address
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderAddress|null $billing_address billing_address
     *
     * @return self
     */
    public function setBillingAddress($billing_address)
    {
        $this->container['billing_address'] = $billing_address;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return \DateTime|null
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime|null $creation_date creation_date
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderCustomer|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderCustomer|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets modified_date
     *
     * @return \DateTime|null
     */
    public function getModifiedDate()
    {
        return $this->container['modified_date'];
    }

    /**
     * Sets modified_date
     *
     * @param \DateTime|null $modified_date modified_date
     *
     * @return self
     */
    public function setModifiedDate($modified_date)
    {
        $this->container['modified_date'] = $modified_date;

        return $this;
    }

    /**
     * Gets offer
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOfferOrder|null
     */
    public function getOffer()
    {
        return $this->container['offer'];
    }

    /**
     * Sets offer
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOfferOrder|null $offer offer
     *
     * @return self
     */
    public function setOffer($offer)
    {
        $this->container['offer'] = $offer;

        return $this;
    }

    /**
     * Gets order_line_list
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderLine[]|null
     */
    public function getOrderLineList()
    {
        return $this->container['order_line_list'];
    }

    /**
     * Sets order_line_list
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderLine[]|null $order_line_list order_line_list
     *
     * @return self
     */
    public function setOrderLineList($order_line_list)
    {
        $this->container['order_line_list'] = $order_line_list;

        return $this;
    }

    /**
     * Gets order_number
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     *
     * @param string|null $order_number order_number
     *
     * @return self
     */
    public function setOrderNumber($order_number)
    {
        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets shipping_address
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderAddress|null
     */
    public function getShippingAddress()
    {
        return $this->container['shipping_address'];
    }

    /**
     * Sets shipping_address
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderAddress|null $shipping_address shipping_address
     *
     * @return self
     */
    public function setShippingAddress($shipping_address)
    {
        $this->container['shipping_address'] = $shipping_address;

        return $this;
    }

    /**
     * Gets initial_total_shipping_charges_amount
     *
     * @return double|null
     */
    public function getInitialTotalShippingChargesAmount()
    {
        return $this->container['initial_total_shipping_charges_amount'];
    }

    /**
     * Sets initial_total_shipping_charges_amount
     *
     * @param double|null $initial_total_shipping_charges_amount initial_total_shipping_charges_amount
     *
     * @return self
     */
    public function setInitialTotalShippingChargesAmount($initial_total_shipping_charges_amount)
    {
        $this->container['initial_total_shipping_charges_amount'] = $initial_total_shipping_charges_amount;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets initial_total_amount
     *
     * @return double|null
     */
    public function getInitialTotalAmount()
    {
        return $this->container['initial_total_amount'];
    }

    /**
     * Sets initial_total_amount
     *
     * @param double|null $initial_total_amount initial_total_amount
     *
     * @return self
     */
    public function setInitialTotalAmount($initial_total_amount)
    {
        $this->container['initial_total_amount'] = $initial_total_amount;

        return $this;
    }

    /**
     * Gets validation_status
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderValidationStatus|null
     */
    public function getValidationStatus()
    {
        return $this->container['validation_status'];
    }

    /**
     * Sets validation_status
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderValidationStatus|null $validation_status validation_status
     *
     * @return self
     */
    public function setValidationStatus($validation_status)
    {
        $this->container['validation_status'] = $validation_status;

        return $this;
    }

    /**
     * Gets shipping_code
     *
     * @return string|null
     */
    public function getShippingCode()
    {
        return $this->container['shipping_code'];
    }

    /**
     * Sets shipping_code
     *
     * @param string|null $shipping_code shipping_code
     *
     * @return self
     */
    public function setShippingCode($shipping_code)
    {
        $this->container['shipping_code'] = $shipping_code;

        return $this;
    }

    /**
     * Gets validated_total_amount
     *
     * @return double|null
     */
    public function getValidatedTotalAmount()
    {
        return $this->container['validated_total_amount'];
    }

    /**
     * Sets validated_total_amount
     *
     * @param double|null $validated_total_amount validated_total_amount
     *
     * @return self
     */
    public function setValidatedTotalAmount($validated_total_amount)
    {
        $this->container['validated_total_amount'] = $validated_total_amount;

        return $this;
    }

    /**
     * Gets shipped_total_amount
     *
     * @return double|null
     */
    public function getShippedTotalAmount()
    {
        return $this->container['shipped_total_amount'];
    }

    /**
     * Sets shipped_total_amount
     *
     * @param double|null $shipped_total_amount shipped_total_amount
     *
     * @return self
     */
    public function setShippedTotalAmount($shipped_total_amount)
    {
        $this->container['shipped_total_amount'] = $shipped_total_amount;

        return $this;
    }

    /**
     * Gets validated_total_shipping_charges
     *
     * @return double|null
     */
    public function getValidatedTotalShippingCharges()
    {
        return $this->container['validated_total_shipping_charges'];
    }

    /**
     * Sets validated_total_shipping_charges
     *
     * @param double|null $validated_total_shipping_charges validated_total_shipping_charges
     *
     * @return self
     */
    public function setValidatedTotalShippingCharges($validated_total_shipping_charges)
    {
        $this->container['validated_total_shipping_charges'] = $validated_total_shipping_charges;

        return $this;
    }

    /**
     * Gets shipped_total_shipping_charges
     *
     * @return double|null
     */
    public function getShippedTotalShippingCharges()
    {
        return $this->container['shipped_total_shipping_charges'];
    }

    /**
     * Sets shipped_total_shipping_charges
     *
     * @param double|null $shipped_total_shipping_charges shipped_total_shipping_charges
     *
     * @return self
     */
    public function setShippedTotalShippingCharges($shipped_total_shipping_charges)
    {
        $this->container['shipped_total_shipping_charges'] = $shipped_total_shipping_charges;

        return $this;
    }

    /**
     * Gets order_state
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderState|null
     */
    public function getOrderState()
    {
        return $this->container['order_state'];
    }

    /**
     * Sets order_state
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderOrderState|null $order_state order_state
     *
     * @return self
     */
    public function setOrderState($order_state)
    {
        $this->container['order_state'] = $order_state;

        return $this;
    }

    /**
     * Gets site_commission_promised_amount
     *
     * @return double|null
     */
    public function getSiteCommissionPromisedAmount()
    {
        return $this->container['site_commission_promised_amount'];
    }

    /**
     * Sets site_commission_promised_amount
     *
     * @param double|null $site_commission_promised_amount site_commission_promised_amount
     *
     * @return self
     */
    public function setSiteCommissionPromisedAmount($site_commission_promised_amount)
    {
        $this->container['site_commission_promised_amount'] = $site_commission_promised_amount;

        return $this;
    }

    /**
     * Gets site_commission_validated_amount
     *
     * @return double|null
     */
    public function getSiteCommissionValidatedAmount()
    {
        return $this->container['site_commission_validated_amount'];
    }

    /**
     * Sets site_commission_validated_amount
     *
     * @param double|null $site_commission_validated_amount site_commission_validated_amount
     *
     * @return self
     */
    public function setSiteCommissionValidatedAmount($site_commission_validated_amount)
    {
        $this->container['site_commission_validated_amount'] = $site_commission_validated_amount;

        return $this;
    }

    /**
     * Gets site_commission_shipped_amount
     *
     * @return double|null
     */
    public function getSiteCommissionShippedAmount()
    {
        return $this->container['site_commission_shipped_amount'];
    }

    /**
     * Sets site_commission_shipped_amount
     *
     * @param double|null $site_commission_shipped_amount site_commission_shipped_amount
     *
     * @return self
     */
    public function setSiteCommissionShippedAmount($site_commission_shipped_amount)
    {
        $this->container['site_commission_shipped_amount'] = $site_commission_shipped_amount;

        return $this;
    }

    /**
     * Gets last_updated_date
     *
     * @return \DateTime|null
     */
    public function getLastUpdatedDate()
    {
        return $this->container['last_updated_date'];
    }

    /**
     * Sets last_updated_date
     *
     * @param \DateTime|null $last_updated_date last_updated_date
     *
     * @return self
     */
    public function setLastUpdatedDate($last_updated_date)
    {
        $this->container['last_updated_date'] = $last_updated_date;

        return $this;
    }

    /**
     * Gets shipping_date_max
     *
     * @return \DateTime|null
     */
    public function getShippingDateMax()
    {
        return $this->container['shipping_date_max'];
    }

    /**
     * Sets shipping_date_max
     *
     * @param \DateTime|null $shipping_date_max shipping_date_max
     *
     * @return self
     */
    public function setShippingDateMax($shipping_date_max)
    {
        $this->container['shipping_date_max'] = $shipping_date_max;

        return $this;
    }

    /**
     * Gets shipping_date_min
     *
     * @return \DateTime|null
     */
    public function getShippingDateMin()
    {
        return $this->container['shipping_date_min'];
    }

    /**
     * Sets shipping_date_min
     *
     * @param \DateTime|null $shipping_date_min shipping_date_min
     *
     * @return self
     */
    public function setShippingDateMin($shipping_date_min)
    {
        $this->container['shipping_date_min'] = $shipping_date_min;

        return $this;
    }

    /**
     * Gets has_claims
     *
     * @return bool|null
     */
    public function getHasClaims()
    {
        return $this->container['has_claims'];
    }

    /**
     * Sets has_claims
     *
     * @param bool|null $has_claims has_claims
     *
     * @return self
     */
    public function setHasClaims($has_claims)
    {
        $this->container['has_claims'] = $has_claims;

        return $this;
    }

    /**
     * Gets is_c_logistique_order
     *
     * @return bool|null
     */
    public function getIsCLogistiqueOrder()
    {
        return $this->container['is_c_logistique_order'];
    }

    /**
     * Sets is_c_logistique_order
     *
     * @param bool|null $is_c_logistique_order is_c_logistique_order
     *
     * @return self
     */
    public function setIsCLogistiqueOrder($is_c_logistique_order)
    {
        $this->container['is_c_logistique_order'] = $is_c_logistique_order;

        return $this;
    }

    /**
     * Gets corporation
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderCorporation|null
     */
    public function getCorporation()
    {
        return $this->container['corporation'];
    }

    /**
     * Sets corporation
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderCorporation|null $corporation corporation
     *
     * @return self
     */
    public function setCorporation($corporation)
    {
        $this->container['corporation'] = $corporation;

        return $this;
    }

    /**
     * Gets visa_cegid
     *
     * @return int|null
     */
    public function getVisaCegid()
    {
        return $this->container['visa_cegid'];
    }

    /**
     * Sets visa_cegid
     *
     * @param int|null $visa_cegid visa_cegid
     *
     * @return self
     */
    public function setVisaCegid($visa_cegid)
    {
        $this->container['visa_cegid'] = $visa_cegid;

        return $this;
    }

    /**
     * Gets partner_order_ref
     *
     * @return string|null
     */
    public function getPartnerOrderRef()
    {
        return $this->container['partner_order_ref'];
    }

    /**
     * Sets partner_order_ref
     *
     * @param string|null $partner_order_ref partner_order_ref
     *
     * @return self
     */
    public function setPartnerOrderRef($partner_order_ref)
    {
        $this->container['partner_order_ref'] = $partner_order_ref;

        return $this;
    }

    /**
     * Gets mod_ges_log
     *
     * @return string|null
     */
    public function getModGesLog()
    {
        return $this->container['mod_ges_log'];
    }

    /**
     * Sets mod_ges_log
     *
     * @param string|null $mod_ges_log mod_ges_log
     *
     * @return self
     */
    public function setModGesLog($mod_ges_log)
    {
        $this->container['mod_ges_log'] = $mod_ges_log;

        return $this;
    }

    /**
     * Gets is_eligibile_substitution
     *
     * @return bool|null
     */
    public function getIsEligibileSubstitution()
    {
        return $this->container['is_eligibile_substitution'];
    }

    /**
     * Sets is_eligibile_substitution
     *
     * @param bool|null $is_eligibile_substitution is_eligibile_substitution
     *
     * @return self
     */
    public function setIsEligibileSubstitution($is_eligibile_substitution)
    {
        $this->container['is_eligibile_substitution'] = $is_eligibile_substitution;

        return $this;
    }

    /**
     * Gets parcel_list
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderParcel[]|null
     */
    public function getParcelList()
    {
        return $this->container['parcel_list'];
    }

    /**
     * Sets parcel_list
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderParcel[]|null $parcel_list parcel_list
     *
     * @return self
     */
    public function setParcelList($parcel_list)
    {
        $this->container['parcel_list'] = $parcel_list;

        return $this;
    }

    /**
     * Gets voucher_list
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderVoucher[]|null
     */
    public function getVoucherList()
    {
        return $this->container['voucher_list'];
    }

    /**
     * Sets voucher_list
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOrderVoucher[]|null $voucher_list voucher_list
     *
     * @return self
     */
    public function setVoucherList($voucher_list)
    {
        $this->container['voucher_list'] = $voucher_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


