<?php
/**
 * CdsMarketplaceApiModelsOffersOfferSortOrder
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOffersOfferSortOrder Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CdsMarketplaceApiModelsOffersOfferSortOrder
{
    /**
     * Possible values of this enum
     */
    const BY_SOLD_QUANTITY_DESCENDING = 'BySoldQuantityDescending';
    const BY_PRICE_ASCENDING = 'ByPriceAscending';
    const BY_PRICE_DESCENDING = 'ByPriceDescending';
    const BY_CREATION_DATE_DESCENDING = 'ByCreationDateDescending';
    const BY_LAST_UPDATED_DATE = 'ByLastUpdatedDate';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BY_SOLD_QUANTITY_DESCENDING,
            self::BY_PRICE_ASCENDING,
            self::BY_PRICE_DESCENDING,
            self::BY_CREATION_DATE_DESCENDING,
            self::BY_LAST_UPDATED_DATE,
        ];
    }
}


