<?php
/**
 * CdsMarketplaceApiModelsOffersSubmissionApiProductCondition
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOffersSubmissionApiProductCondition Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CdsMarketplaceApiModelsOffersSubmissionApiProductCondition
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'Unknown';
    const LIKE_NEW = 'LikeNew';
    const VERY_GOOD_STATE = 'VeryGoodState';
    const GOOD_STATE = 'GoodState';
    const AVERAGE_STATE = 'AverageState';
    const REFURBISHED = 'Refurbished';
    const _NEW = 'New';
    const _EMPTY = 'Empty';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::LIKE_NEW,
            self::VERY_GOOD_STATE,
            self::GOOD_STATE,
            self::AVERAGE_STATE,
            self::REFURBISHED,
            self::_NEW,
            self::_EMPTY,
        ];
    }
}


