<?php
/**
 * CdsMarketplaceApiModelsOffersSubmissionApiShippingDeliveryMode
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOffersSubmissionApiShippingDeliveryMode Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CdsMarketplaceApiModelsOffersSubmissionApiShippingDeliveryMode
{
    /**
     * Possible values of this enum
     */
    const NONE = 'None';
    const STANDARD = 'Standard';
    const TRACKED = 'Tracked';
    const REGISTERED = 'Registered';
    const RIM = 'Rim';
    const RELAY = 'Relay';
    const MONDIAL_RELAY = 'MondialRelay';
    const RELAIS_COLIS = 'RelaisColis';
    const SO_COLISSIMO = 'SoColissimo';
    const BIG_PARCEL_ECO = 'BigParcelEco';
    const BIG_PARCEL_STANDARD = 'BigParcelStandard';
    const BIG_PARCEL_COMFORT = 'BigParcelComfort';
    const EXPRESS = 'Express';
    const FAST = 'Fast';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::STANDARD,
            self::TRACKED,
            self::REGISTERED,
            self::RIM,
            self::RELAY,
            self::MONDIAL_RELAY,
            self::RELAIS_COLIS,
            self::SO_COLISSIMO,
            self::BIG_PARCEL_ECO,
            self::BIG_PARCEL_STANDARD,
            self::BIG_PARCEL_COMFORT,
            self::EXPRESS,
            self::FAST,
        ];
    }
}


