<?php
/**
 * CdsMarketplaceApiModelsOffersOffer
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOffersOffer Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CdsMarketplaceApiModelsOffersOffer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cds.MarketplaceApi.Models.Offers.Offer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'offer_id' => 'int',
        'offer_state' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosOfferStateDto',
        'comments' => 'string',
        'cdiscount_product_id' => 'string',
        'seller_product_id' => 'string',
        'product_ean' => 'string',
        'parent_product_id' => 'string',
        'product_state' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosProductStateDto',
        'product_condition_id' => 'int',
        'product_condition_name' => 'string',
        'display_name' => 'string',
        'price' => 'double',
        'eco_tax' => 'double',
        'vat_rate' => 'double',
        'dea_tax' => 'double',
        'price_must_be_aligned' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosPriceAlignmentActionDto',
        'minimum_price_for_price_alignment' => 'double',
        'best_shipping_charges' => 'double',
        'product_packaging_unit' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosProductPackagingUnitDto',
        'product_packaging_unit_price' => 'double',
        'product_packaging_value' => 'double',
        'striked_price' => 'double',
        'shipping_information_list' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersShippingInformation[]',
        'creation_date' => '\DateTime',
        'last_update_date' => '\DateTime',
        'offer_pool_list' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersOfferPool[]',
        'sold_out_management' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosSoldOutManagementDto',
        'logistic_management' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosLogisticManagementDto',
        'stocks' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersStock[]',
        'discount_informations' => '\OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDiscount'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'offer_id' => 'int64',
        'offer_state' => null,
        'comments' => null,
        'cdiscount_product_id' => null,
        'seller_product_id' => null,
        'product_ean' => null,
        'parent_product_id' => null,
        'product_state' => null,
        'product_condition_id' => 'int32',
        'product_condition_name' => null,
        'display_name' => null,
        'price' => 'double',
        'eco_tax' => 'double',
        'vat_rate' => 'double',
        'dea_tax' => 'double',
        'price_must_be_aligned' => null,
        'minimum_price_for_price_alignment' => 'double',
        'best_shipping_charges' => 'double',
        'product_packaging_unit' => null,
        'product_packaging_unit_price' => 'double',
        'product_packaging_value' => 'double',
        'striked_price' => 'double',
        'shipping_information_list' => null,
        'creation_date' => 'date-time',
        'last_update_date' => 'date-time',
        'offer_pool_list' => null,
        'sold_out_management' => null,
        'logistic_management' => null,
        'stocks' => null,
        'discount_informations' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'offer_id' => 'offer_id',
        'offer_state' => 'offer_state',
        'comments' => 'comments',
        'cdiscount_product_id' => 'cdiscount_product_id',
        'seller_product_id' => 'seller_product_id',
        'product_ean' => 'product_ean',
        'parent_product_id' => 'parent_product_id',
        'product_state' => 'product_state',
        'product_condition_id' => 'product_condition_id',
        'product_condition_name' => 'product_condition_name',
        'display_name' => 'display_name',
        'price' => 'price',
        'eco_tax' => 'eco_tax',
        'vat_rate' => 'vat_rate',
        'dea_tax' => 'dea_tax',
        'price_must_be_aligned' => 'price_must_be_aligned',
        'minimum_price_for_price_alignment' => 'minimum_price_for_price_alignment',
        'best_shipping_charges' => 'best_shipping_charges',
        'product_packaging_unit' => 'product_packaging_unit',
        'product_packaging_unit_price' => 'product_packaging_unit_price',
        'product_packaging_value' => 'product_packaging_value',
        'striked_price' => 'striked_price',
        'shipping_information_list' => 'shipping_information_list',
        'creation_date' => 'creation_date',
        'last_update_date' => 'last_update_date',
        'offer_pool_list' => 'offer_pool_list',
        'sold_out_management' => 'sold_out_management',
        'logistic_management' => 'logistic_management',
        'stocks' => 'stocks',
        'discount_informations' => 'discount_informations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'offer_id' => 'setOfferId',
        'offer_state' => 'setOfferState',
        'comments' => 'setComments',
        'cdiscount_product_id' => 'setCdiscountProductId',
        'seller_product_id' => 'setSellerProductId',
        'product_ean' => 'setProductEan',
        'parent_product_id' => 'setParentProductId',
        'product_state' => 'setProductState',
        'product_condition_id' => 'setProductConditionId',
        'product_condition_name' => 'setProductConditionName',
        'display_name' => 'setDisplayName',
        'price' => 'setPrice',
        'eco_tax' => 'setEcoTax',
        'vat_rate' => 'setVatRate',
        'dea_tax' => 'setDeaTax',
        'price_must_be_aligned' => 'setPriceMustBeAligned',
        'minimum_price_for_price_alignment' => 'setMinimumPriceForPriceAlignment',
        'best_shipping_charges' => 'setBestShippingCharges',
        'product_packaging_unit' => 'setProductPackagingUnit',
        'product_packaging_unit_price' => 'setProductPackagingUnitPrice',
        'product_packaging_value' => 'setProductPackagingValue',
        'striked_price' => 'setStrikedPrice',
        'shipping_information_list' => 'setShippingInformationList',
        'creation_date' => 'setCreationDate',
        'last_update_date' => 'setLastUpdateDate',
        'offer_pool_list' => 'setOfferPoolList',
        'sold_out_management' => 'setSoldOutManagement',
        'logistic_management' => 'setLogisticManagement',
        'stocks' => 'setStocks',
        'discount_informations' => 'setDiscountInformations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'offer_id' => 'getOfferId',
        'offer_state' => 'getOfferState',
        'comments' => 'getComments',
        'cdiscount_product_id' => 'getCdiscountProductId',
        'seller_product_id' => 'getSellerProductId',
        'product_ean' => 'getProductEan',
        'parent_product_id' => 'getParentProductId',
        'product_state' => 'getProductState',
        'product_condition_id' => 'getProductConditionId',
        'product_condition_name' => 'getProductConditionName',
        'display_name' => 'getDisplayName',
        'price' => 'getPrice',
        'eco_tax' => 'getEcoTax',
        'vat_rate' => 'getVatRate',
        'dea_tax' => 'getDeaTax',
        'price_must_be_aligned' => 'getPriceMustBeAligned',
        'minimum_price_for_price_alignment' => 'getMinimumPriceForPriceAlignment',
        'best_shipping_charges' => 'getBestShippingCharges',
        'product_packaging_unit' => 'getProductPackagingUnit',
        'product_packaging_unit_price' => 'getProductPackagingUnitPrice',
        'product_packaging_value' => 'getProductPackagingValue',
        'striked_price' => 'getStrikedPrice',
        'shipping_information_list' => 'getShippingInformationList',
        'creation_date' => 'getCreationDate',
        'last_update_date' => 'getLastUpdateDate',
        'offer_pool_list' => 'getOfferPoolList',
        'sold_out_management' => 'getSoldOutManagement',
        'logistic_management' => 'getLogisticManagement',
        'stocks' => 'getStocks',
        'discount_informations' => 'getDiscountInformations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['offer_id'] = $data['offer_id'] ?? null;
        $this->container['offer_state'] = $data['offer_state'] ?? null;
        $this->container['comments'] = $data['comments'] ?? null;
        $this->container['cdiscount_product_id'] = $data['cdiscount_product_id'] ?? null;
        $this->container['seller_product_id'] = $data['seller_product_id'] ?? null;
        $this->container['product_ean'] = $data['product_ean'] ?? null;
        $this->container['parent_product_id'] = $data['parent_product_id'] ?? null;
        $this->container['product_state'] = $data['product_state'] ?? null;
        $this->container['product_condition_id'] = $data['product_condition_id'] ?? null;
        $this->container['product_condition_name'] = $data['product_condition_name'] ?? null;
        $this->container['display_name'] = $data['display_name'] ?? null;
        $this->container['price'] = $data['price'] ?? null;
        $this->container['eco_tax'] = $data['eco_tax'] ?? null;
        $this->container['vat_rate'] = $data['vat_rate'] ?? null;
        $this->container['dea_tax'] = $data['dea_tax'] ?? null;
        $this->container['price_must_be_aligned'] = $data['price_must_be_aligned'] ?? null;
        $this->container['minimum_price_for_price_alignment'] = $data['minimum_price_for_price_alignment'] ?? null;
        $this->container['best_shipping_charges'] = $data['best_shipping_charges'] ?? null;
        $this->container['product_packaging_unit'] = $data['product_packaging_unit'] ?? null;
        $this->container['product_packaging_unit_price'] = $data['product_packaging_unit_price'] ?? null;
        $this->container['product_packaging_value'] = $data['product_packaging_value'] ?? null;
        $this->container['striked_price'] = $data['striked_price'] ?? null;
        $this->container['shipping_information_list'] = $data['shipping_information_list'] ?? null;
        $this->container['creation_date'] = $data['creation_date'] ?? null;
        $this->container['last_update_date'] = $data['last_update_date'] ?? null;
        $this->container['offer_pool_list'] = $data['offer_pool_list'] ?? null;
        $this->container['sold_out_management'] = $data['sold_out_management'] ?? null;
        $this->container['logistic_management'] = $data['logistic_management'] ?? null;
        $this->container['stocks'] = $data['stocks'] ?? null;
        $this->container['discount_informations'] = $data['discount_informations'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets offer_id
     *
     * @return int|null
     */
    public function getOfferId()
    {
        return $this->container['offer_id'];
    }

    /**
     * Sets offer_id
     *
     * @param int|null $offer_id offer_id
     *
     * @return self
     */
    public function setOfferId($offer_id)
    {
        $this->container['offer_id'] = $offer_id;

        return $this;
    }

    /**
     * Gets offer_state
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosOfferStateDto|null
     */
    public function getOfferState()
    {
        return $this->container['offer_state'];
    }

    /**
     * Sets offer_state
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosOfferStateDto|null $offer_state offer_state
     *
     * @return self
     */
    public function setOfferState($offer_state)
    {
        $this->container['offer_state'] = $offer_state;

        return $this;
    }

    /**
     * Gets comments
     *
     * @return string|null
     */
    public function getComments()
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param string|null $comments comments
     *
     * @return self
     */
    public function setComments($comments)
    {
        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets cdiscount_product_id
     *
     * @return string|null
     */
    public function getCdiscountProductId()
    {
        return $this->container['cdiscount_product_id'];
    }

    /**
     * Sets cdiscount_product_id
     *
     * @param string|null $cdiscount_product_id cdiscount_product_id
     *
     * @return self
     */
    public function setCdiscountProductId($cdiscount_product_id)
    {
        $this->container['cdiscount_product_id'] = $cdiscount_product_id;

        return $this;
    }

    /**
     * Gets seller_product_id
     *
     * @return string|null
     */
    public function getSellerProductId()
    {
        return $this->container['seller_product_id'];
    }

    /**
     * Sets seller_product_id
     *
     * @param string|null $seller_product_id seller_product_id
     *
     * @return self
     */
    public function setSellerProductId($seller_product_id)
    {
        $this->container['seller_product_id'] = $seller_product_id;

        return $this;
    }

    /**
     * Gets product_ean
     *
     * @return string|null
     */
    public function getProductEan()
    {
        return $this->container['product_ean'];
    }

    /**
     * Sets product_ean
     *
     * @param string|null $product_ean product_ean
     *
     * @return self
     */
    public function setProductEan($product_ean)
    {
        $this->container['product_ean'] = $product_ean;

        return $this;
    }

    /**
     * Gets parent_product_id
     *
     * @return string|null
     */
    public function getParentProductId()
    {
        return $this->container['parent_product_id'];
    }

    /**
     * Sets parent_product_id
     *
     * @param string|null $parent_product_id parent_product_id
     *
     * @return self
     */
    public function setParentProductId($parent_product_id)
    {
        $this->container['parent_product_id'] = $parent_product_id;

        return $this;
    }

    /**
     * Gets product_state
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosProductStateDto|null
     */
    public function getProductState()
    {
        return $this->container['product_state'];
    }

    /**
     * Sets product_state
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosProductStateDto|null $product_state product_state
     *
     * @return self
     */
    public function setProductState($product_state)
    {
        $this->container['product_state'] = $product_state;

        return $this;
    }

    /**
     * Gets product_condition_id
     *
     * @return int|null
     */
    public function getProductConditionId()
    {
        return $this->container['product_condition_id'];
    }

    /**
     * Sets product_condition_id
     *
     * @param int|null $product_condition_id product_condition_id
     *
     * @return self
     */
    public function setProductConditionId($product_condition_id)
    {
        $this->container['product_condition_id'] = $product_condition_id;

        return $this;
    }

    /**
     * Gets product_condition_name
     *
     * @return string|null
     */
    public function getProductConditionName()
    {
        return $this->container['product_condition_name'];
    }

    /**
     * Sets product_condition_name
     *
     * @param string|null $product_condition_name product_condition_name
     *
     * @return self
     */
    public function setProductConditionName($product_condition_name)
    {
        $this->container['product_condition_name'] = $product_condition_name;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets price
     *
     * @return double|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param double|null $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets eco_tax
     *
     * @return double|null
     */
    public function getEcoTax()
    {
        return $this->container['eco_tax'];
    }

    /**
     * Sets eco_tax
     *
     * @param double|null $eco_tax eco_tax
     *
     * @return self
     */
    public function setEcoTax($eco_tax)
    {
        $this->container['eco_tax'] = $eco_tax;

        return $this;
    }

    /**
     * Gets vat_rate
     *
     * @return double|null
     */
    public function getVatRate()
    {
        return $this->container['vat_rate'];
    }

    /**
     * Sets vat_rate
     *
     * @param double|null $vat_rate vat_rate
     *
     * @return self
     */
    public function setVatRate($vat_rate)
    {
        $this->container['vat_rate'] = $vat_rate;

        return $this;
    }

    /**
     * Gets dea_tax
     *
     * @return double|null
     */
    public function getDeaTax()
    {
        return $this->container['dea_tax'];
    }

    /**
     * Sets dea_tax
     *
     * @param double|null $dea_tax dea_tax
     *
     * @return self
     */
    public function setDeaTax($dea_tax)
    {
        $this->container['dea_tax'] = $dea_tax;

        return $this;
    }

    /**
     * Gets price_must_be_aligned
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosPriceAlignmentActionDto|null
     */
    public function getPriceMustBeAligned()
    {
        return $this->container['price_must_be_aligned'];
    }

    /**
     * Sets price_must_be_aligned
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosPriceAlignmentActionDto|null $price_must_be_aligned price_must_be_aligned
     *
     * @return self
     */
    public function setPriceMustBeAligned($price_must_be_aligned)
    {
        $this->container['price_must_be_aligned'] = $price_must_be_aligned;

        return $this;
    }

    /**
     * Gets minimum_price_for_price_alignment
     *
     * @return double|null
     */
    public function getMinimumPriceForPriceAlignment()
    {
        return $this->container['minimum_price_for_price_alignment'];
    }

    /**
     * Sets minimum_price_for_price_alignment
     *
     * @param double|null $minimum_price_for_price_alignment minimum_price_for_price_alignment
     *
     * @return self
     */
    public function setMinimumPriceForPriceAlignment($minimum_price_for_price_alignment)
    {
        $this->container['minimum_price_for_price_alignment'] = $minimum_price_for_price_alignment;

        return $this;
    }

    /**
     * Gets best_shipping_charges
     *
     * @return double|null
     */
    public function getBestShippingCharges()
    {
        return $this->container['best_shipping_charges'];
    }

    /**
     * Sets best_shipping_charges
     *
     * @param double|null $best_shipping_charges best_shipping_charges
     *
     * @return self
     */
    public function setBestShippingCharges($best_shipping_charges)
    {
        $this->container['best_shipping_charges'] = $best_shipping_charges;

        return $this;
    }

    /**
     * Gets product_packaging_unit
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosProductPackagingUnitDto|null
     */
    public function getProductPackagingUnit()
    {
        return $this->container['product_packaging_unit'];
    }

    /**
     * Sets product_packaging_unit
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosProductPackagingUnitDto|null $product_packaging_unit product_packaging_unit
     *
     * @return self
     */
    public function setProductPackagingUnit($product_packaging_unit)
    {
        $this->container['product_packaging_unit'] = $product_packaging_unit;

        return $this;
    }

    /**
     * Gets product_packaging_unit_price
     *
     * @return double|null
     */
    public function getProductPackagingUnitPrice()
    {
        return $this->container['product_packaging_unit_price'];
    }

    /**
     * Sets product_packaging_unit_price
     *
     * @param double|null $product_packaging_unit_price product_packaging_unit_price
     *
     * @return self
     */
    public function setProductPackagingUnitPrice($product_packaging_unit_price)
    {
        $this->container['product_packaging_unit_price'] = $product_packaging_unit_price;

        return $this;
    }

    /**
     * Gets product_packaging_value
     *
     * @return double|null
     */
    public function getProductPackagingValue()
    {
        return $this->container['product_packaging_value'];
    }

    /**
     * Sets product_packaging_value
     *
     * @param double|null $product_packaging_value product_packaging_value
     *
     * @return self
     */
    public function setProductPackagingValue($product_packaging_value)
    {
        $this->container['product_packaging_value'] = $product_packaging_value;

        return $this;
    }

    /**
     * Gets striked_price
     *
     * @return double|null
     */
    public function getStrikedPrice()
    {
        return $this->container['striked_price'];
    }

    /**
     * Sets striked_price
     *
     * @param double|null $striked_price striked_price
     *
     * @return self
     */
    public function setStrikedPrice($striked_price)
    {
        $this->container['striked_price'] = $striked_price;

        return $this;
    }

    /**
     * Gets shipping_information_list
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersShippingInformation[]|null
     */
    public function getShippingInformationList()
    {
        return $this->container['shipping_information_list'];
    }

    /**
     * Sets shipping_information_list
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersShippingInformation[]|null $shipping_information_list shipping_information_list
     *
     * @return self
     */
    public function setShippingInformationList($shipping_information_list)
    {
        $this->container['shipping_information_list'] = $shipping_information_list;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return \DateTime|null
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime|null $creation_date creation_date
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets last_update_date
     *
     * @return \DateTime|null
     */
    public function getLastUpdateDate()
    {
        return $this->container['last_update_date'];
    }

    /**
     * Sets last_update_date
     *
     * @param \DateTime|null $last_update_date last_update_date
     *
     * @return self
     */
    public function setLastUpdateDate($last_update_date)
    {
        $this->container['last_update_date'] = $last_update_date;

        return $this;
    }

    /**
     * Gets offer_pool_list
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersOfferPool[]|null
     */
    public function getOfferPoolList()
    {
        return $this->container['offer_pool_list'];
    }

    /**
     * Sets offer_pool_list
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersOfferPool[]|null $offer_pool_list offer_pool_list
     *
     * @return self
     */
    public function setOfferPoolList($offer_pool_list)
    {
        $this->container['offer_pool_list'] = $offer_pool_list;

        return $this;
    }

    /**
     * Gets sold_out_management
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosSoldOutManagementDto|null
     */
    public function getSoldOutManagement()
    {
        return $this->container['sold_out_management'];
    }

    /**
     * Sets sold_out_management
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosSoldOutManagementDto|null $sold_out_management sold_out_management
     *
     * @return self
     */
    public function setSoldOutManagement($sold_out_management)
    {
        $this->container['sold_out_management'] = $sold_out_management;

        return $this;
    }

    /**
     * Gets logistic_management
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosLogisticManagementDto|null
     */
    public function getLogisticManagement()
    {
        return $this->container['logistic_management'];
    }

    /**
     * Sets logistic_management
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDtosLogisticManagementDto|null $logistic_management logistic_management
     *
     * @return self
     */
    public function setLogisticManagement($logistic_management)
    {
        $this->container['logistic_management'] = $logistic_management;

        return $this;
    }

    /**
     * Gets stocks
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersStock[]|null
     */
    public function getStocks()
    {
        return $this->container['stocks'];
    }

    /**
     * Sets stocks
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersStock[]|null $stocks stocks
     *
     * @return self
     */
    public function setStocks($stocks)
    {
        $this->container['stocks'] = $stocks;

        return $this;
    }

    /**
     * Gets discount_informations
     *
     * @return \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDiscount|null
     */
    public function getDiscountInformations()
    {
        return $this->container['discount_informations'];
    }

    /**
     * Sets discount_informations
     *
     * @param \OpenAPI\Client\Model\CdsMarketplaceApiModelsOffersDiscount|null $discount_informations discount_informations
     *
     * @return self
     */
    public function setDiscountInformations($discount_informations)
    {
        $this->container['discount_informations'] = $discount_informations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


