<?php
/**
 * CdsMarketplaceApiModelsOrderOrderStateEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdsMarketplaceApiModelsOrderOrderStateEnum Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CdsMarketplaceApiModelsOrderOrderStateEnum
{
    /**
     * Possible values of this enum
     */
    const CANCELLED_BY_CUSTOMER = 'CancelledByCustomer';
    const WAITING_FOR_SELLER_ACCEPTATION = 'WaitingForSellerAcceptation';
    const ACCEPTED_BY_SELLER = 'AcceptedBySeller';
    const PAYMENT_IN_PROGRESS = 'PaymentInProgress';
    const WAITING_FOR_SHIPMENT_ACCEPTATION = 'WaitingForShipmentAcceptation';
    const SHIPPED = 'Shipped';
    const REFUSED_BY_SELLER = 'RefusedBySeller';
    const AUTOMATIC_CANCELLATION = 'AutomaticCancellation';
    const PAYMENT_REFUSED = 'PaymentRefused';
    const SHIPMENT_REFUSED_BY_SELLER = 'ShipmentRefusedBySeller';
    const NONE = 'None';
    const VALIDATED_FIANET = 'ValidatedFianet';
    const REFUSED_NO_SHIPMENT = 'RefusedNoShipment';
    const AVAILABLE_ON_STORE = 'AvailableOnStore';
    const NON_PICKED_UP_BY_CUSTOMER = 'NonPickedUpByCustomer';
    const PICKED_UP = 'PickedUp';
    const SERVICE_CANCELED = 'ServiceCanceled';
    const PENDING_SHIPMENT_FOR_ASSOCIATED_PRODUCT = 'PendingShipmentForAssociatedProduct';
    const BLOCKED_WAITING_FOR_TREATMENT = 'BlockedWaitingForTreatment';
    const BLOCKED_WAITING_FOR_PROOF = 'BlockedWaitingForProof';
    const BLOCKED_REPEATED_LITIGATION_SUSPICION = 'BlockedRepeatedLitigationSuspicion';
    const BLOCKED_FRAUD_SUSPICION = 'BlockedFraudSuspicion';
    const BLOCKED_CONFIRMED = 'BlockedConfirmed';
    const FINISHED_GENERIX_UPDATE = 'FinishedGenerixUpdate';
    const BLOCKED_REPEATED_LITIGATION_SUSPICION_CONFIRMATION = 'BlockedRepeatedLitigationSuspicionConfirmation';
    const BLOCKED_FRAUD_SUSPICION_CONFIRMATION = 'BlockedFraudSuspicionConfirmation';
    const CEGID_DOWN = 'CegidDown';
    const BLOCKED_AUTOMATIC_CDS = 'BlockedAutomaticCds';
    const BEING_CANCELLED = 'BeingCancelled';
    const BEING_MODIFIED = 'BeingModified';
    const REQUEST_GOING_TO_GNX = 'RequestGoingToGnx';
    const PARTIAL_IN_GNX = 'PartialInGnx';
    const BEING_VALIDATED_FIANET = 'BeingValidatedFianet';
    const BLOCKED_MARKETPLACE_SERVICE = 'BlockedMarketplaceService';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CANCELLED_BY_CUSTOMER,
            self::WAITING_FOR_SELLER_ACCEPTATION,
            self::ACCEPTED_BY_SELLER,
            self::PAYMENT_IN_PROGRESS,
            self::WAITING_FOR_SHIPMENT_ACCEPTATION,
            self::SHIPPED,
            self::REFUSED_BY_SELLER,
            self::AUTOMATIC_CANCELLATION,
            self::PAYMENT_REFUSED,
            self::SHIPMENT_REFUSED_BY_SELLER,
            self::NONE,
            self::VALIDATED_FIANET,
            self::REFUSED_NO_SHIPMENT,
            self::AVAILABLE_ON_STORE,
            self::NON_PICKED_UP_BY_CUSTOMER,
            self::PICKED_UP,
            self::SERVICE_CANCELED,
            self::PENDING_SHIPMENT_FOR_ASSOCIATED_PRODUCT,
            self::BLOCKED_WAITING_FOR_TREATMENT,
            self::BLOCKED_WAITING_FOR_PROOF,
            self::BLOCKED_REPEATED_LITIGATION_SUSPICION,
            self::BLOCKED_FRAUD_SUSPICION,
            self::BLOCKED_CONFIRMED,
            self::FINISHED_GENERIX_UPDATE,
            self::BLOCKED_REPEATED_LITIGATION_SUSPICION_CONFIRMATION,
            self::BLOCKED_FRAUD_SUSPICION_CONFIRMATION,
            self::CEGID_DOWN,
            self::BLOCKED_AUTOMATIC_CDS,
            self::BEING_CANCELLED,
            self::BEING_MODIFIED,
            self::REQUEST_GOING_TO_GNX,
            self::PARTIAL_IN_GNX,
            self::BEING_VALIDATED_FIANET,
            self::BLOCKED_MARKETPLACE_SERVICE,
        ];
    }
}


